---
title: "Untitled"
author: "Jyotishman Bandyopadhyay"
date: "28/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(keras)
mnist <- suppressMessages(dataset_mnist())
c(c(train_images, train_labels), c(test_images, test_labels)) %<-% mnist

```

```{r}
digit <- train_images[1,,]
plot(as.raster(digit, max = 255))
```

# Data Set:

## Train Set
```{r}
train_images<-array_reshape(train_images,c(60000,28*28))
train_images<-train_images/255
str(train_images)
```
## Test Set
```{r}
test_images<-array_reshape(test_images,c(10000,28*28))
str(test_images)
test_images<-test_images/255
```

# One Hot Encoding
```{r}
train_labels<-to_categorical(train_labels)
str(train_labels)
test_labels<-to_categorical(test_labels)
str(test_labels)
```

# Model
```{r}
model<-keras_model_sequential()%>%layer_dense(units = 512,activation = "relu",input_shape = 28*28)%>%layer_dense(units = 10,activation = "softmax")
model
```
```{r}
model%>%compile(optimizer="rmsprop",loss="categorical_crossentropy",metric="accuracy")
```

```{r}
history<-network%>%fit(train_images,train_labels,epochs = 5,batch_size=128)
```

